### ISSUE TITLE
Bug: Peer Dependency Conflict with `@middy/core` in Version 1.13.0

### ISSUE THREAD

**Issue by domengabrovsek** [aws-powertools/powertools-lambda-typescript#1702] opened 2023-09-21 08:56 UTC
### Expected Behaviour

This issue forces us to pin the logger version to 1.12.1 to avoid the build failure. It would be great if the peer dependencies could be aligned to support the latest versions of both packages.

`npm install` should complete without errors.

### Current Behaviour

Up until now, I was using @aws-lambda-powertools/logger version ^1.12.1 and @middy/core version ^4.5.5 in my package.json. Since version 1.13.0 was released, my npm install fails with this error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @aws-lambda-powertools/logger@1.13.0
npm ERR! Found: @middy/core@4.6.4
npm ERR! node_modules/@middy/core
npm ERR!   @middy/core@"^4.5.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @middy/core@">=3.x <4.x" from @aws-lambda-powertools/logger@1.13.0
npm ERR! node_modules/@aws-lambda-powertools/logger
npm ERR!   @aws-lambda-powertools/logger@"^1.12.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @middy/core@3.6.2
npm ERR! node_modules/@middy/core
npm ERR!   peerOptional @middy/core@">=3.x <4.x" from @aws-lambda-powertools/logger@1.13.0
npm ERR!   node_modules/@aws-lambda-powertools/logger
npm ERR!     @aws-lambda-powertools/logger@"^1.12.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/domengabrovsek/.npm/_logs/2023-09-21T08_42_49_919Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/domengabrovsek/.npm/_logs/2023-09-21T08_42_49_919Z-debug-0.log
```

Upgrading to `@aws-lambda-powertools/logger@1.13.0` breaks the build due to a peer dependency conflict with `@middy/core`.

### Code snippet

not applicable

### Steps to Reproduce

1. Have the following `package.json` in your project:
   ```json
   {
     "dependencies": {
       "@aws-lambda-powertools/logger": "^1.12.1",
       "@middy/core": "^4.5.5"
     }
   }
   ```
2. Run `npm install`

OR

clone this repo `https://github.com/domengabrovsek/aws-powertools-repro` and run `npm install`

### Powertools for AWS Lambda (TypeScript) version

1.13.0

### AWS Lambda function runtime

18.x

### Packaging format used

npm

**Comment by am29d** [comment] 2023-09-21 09:14
Hey @domengabrovsek thanks for raising the issue and apologies for the failed build caused by the new version. 

We only support middy 3.x, and added only recently the peer dependency to make it explicit. As mentioned in #1694 we are very close to drop node14 support and can start moving to middy 4.x. in our major v2 release.

**Comment by domengabrovsek** [comment] 2023-09-21 09:24
Thank you @am29d for the explanation. 

It surprised me because the build started failing without any changes on my side and I didn't notice any breaking changes related to this. I have been using tracer, logger, and metrics with middy 4.x for some time now and it has worked well. I'll pin the versions for now so I can continue working. 

Thank you for everything you're doing with the powertools, it's a pleasure to use them!

**Comment by dreamorosi** [comment] 2023-09-21 09:27
Hi @domengabrovsek, thank you for opening this issue. As Alex mentioned this is something that was already documented both [our documentation](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#capturing-lambda-context-info)(see callout titled "A note about Middy") and Middy's documentation ([here](https://middy.js.org/docs/integrations/lambda-powertools)), however we should not have made this change in a minor release like we did.

We will make another emergency release today and remove the peer dependency. Then we'll revisit the topic in our next major version.

**Comment by am29d** [comment] 2023-09-21 09:29
Hey @domengabrovsek ,  it was great that it worked with 4.x before 😄 . 

@dreamorosi and I had a chat and we agreed that it'd be best to remove the upper bound on middy 4.x to unblock you and potentially many others. I will make a quick release soon. 

Thanks again for raising this issue, which helps us to address breaking builds quickly 🙏.

**Comment by alenkoso** [comment] 2023-09-21 09:38
This is pretty wholesome, how you guys have responded so rapidly and even offered to help the community with a new release. :)

**Closed** 2023-09-21 10:07 UTC
