### ISSUE TITLE
Maintenance: add missing `resetKeys` method to `LoggerInterface`

### ISSUE THREAD

**Issue by ralbertazzi** [aws-powertools/powertools-lambda-typescript#3212] opened 2024-10-17 10:16 UTC
### Expected Behavior

Being able to call `logger.resetKeys()` without getting typescript compilation errors.

### Current Behavior

`logger.resetKeys()` results in a typescript error `Property 'resetKeys' does not exist on type 'Logger'`. I believe this is because [LoggerInterface](https://github.com/aws-powertools/powertools-lambda-typescript/blob/02b0bd6dfc07e57f67909f86aae706ba01bd3298/packages/logger/src/types/Logger.ts#L181-L205) does not define `resetKeys()`.

### Code snippet

```typescript
const logger = new Logger();
logger.resetKeys();
```

### Steps to Reproduce

Compile with Typescript strict settings

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment] 2024-10-17 10:59
Hi, thanks for opening this issue.

The method is indeed missing from the interface, however I am both unable to reproduce the issue using the steps you described and inclined to change the definition of this issue.

Because this is, by definition, a compile time error - it's not a bug under [the classification for this project](https://docs.powertools.aws.dev/lambda/typescript/latest/maintainers/#is-that-a-bug) (aka bugs must [...] produces [sic] incorrect or unexpected results at runtime that differ from its intended behavior.).

In terms of reproducing the bug, I just started a new sample project from scratch and using the `tsconfig.json` below, which includes `"strict": true` I am able to compile the code (by running `npx tsc -p tsconfig.json`) you mentioned above without seeing any error.

<details>

```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "lib": [
      "es2022"
    ],
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "cdk.out"
  ]
}
```

</details>

We'll be adding the missing method to the interface, however it'd be helpful to understand the use case to see if there's anything else we are missing and can improve in our docs.

**Comment by dreamorosi** [comment] 2024-10-17 11:01
Also, I have added this to the backlog and added the `help-wanted` label.

If you want to ensure that it will included in the next release (next Tuesday), feel free to send a PR and I'll be happy to help you get it merged.

**Comment by ralbertazzi** [comment] 2024-10-17 11:41
There you go ;) https://github.com/aws-powertools/powertools-lambda-typescript/pull/3213

**Closed** 2024-10-17 13:44 UTC
Labels: help-wanted, logger
