### ISSUE TITLE
Feature request: Aggregated Metics

### ISSUE THREAD

**Issue by alan-churley** [aws-powertools/powertools-lambda-typescript#142] opened 2021-07-27 15:21 UTC
Currently the metics module is not capable of supporting Aggregated Metrics, as per https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html#publishingDataPoints1

It would be good to investigate supporting this functionality

**Comment by dreamorosi** [comment] 2022-11-09 15:24
The issue is still current so contributions are welcome, however the first action item should be to investigate if this feature is feasible and/or it makes sense in the context of [EMF metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html) which we are using today.

After investigating we'll decide if there's anything to implement or not, and if not we'll use this issue to document the decision.

This is a good issue for newcomers as well as people who want to contribute to the library but don't want to commit to making code changes.

If anyone is interested in picking this up, please leave a comment here, then discuss your findings and proposed changes before opening a PR.

**Comment by dreamorosi** [comment] 2023-06-22 16:59
I have researched this and so far I haven't been able to find any mention to aggregated metrics in the EMF specification.

I'm going to close the issue for now, if anyone stumbles into this and has additional info/use cases please feel free to open a new one.

**Closed by dreamorosi** 2023-06-22 16:59 UTC
Labels: metrics
