### ISSUE TITLE
Bug: @tracer.captureMethod() is not bound to the decorated class

### ISSUE THREAD

**Issue by ratscrew** [aws-powertools/powertools-lambda-typescript#1028] opened 2022-07-27 15:49 UTC
## Bug description

The @tracer.captureMethod() decorator is bound to the decorator not the class its decorating.

```
export class Lambda implements LambdaInterface {
   @tracer.captureMethod()
   myMethod(){

      //other method is undefined as "this" is no longer the Lambda class
      this.otherMethod()
   }

   otherMethod(){}
}
```

### Expected Behavior

`` this.otherMethod() `` should call the `` this.otherMethod() `` in the same class

### Current Behavior

`` this.otherMethod() `` is undefined

### Possible Solution

see #1026 
the `@tracer.captureLambdaHandler()` decorator already does this

### Steps to Reproduce

1. create a class with two or methods in it
2. add the decorator ``@tracer.captureMethod()`` to one or more of the function
3. call another method or prop in the decorated method
4. the method or prop will be undefined

### Environment

* **Powertools version used**: 1.0.2
* **Packaging format (Layers, npm)**:
* **AWS Lambda function runtime:**
* **Debugging logs:**

### Related issues, RFCs

 #1026

**Comment by dreamorosi** [comment] 2022-07-27 15:57
Thank you for opening the issue, appreciate your time.

I was able to reproduce the bug described using this code:

```ts
import { Tracer } from "@aws-lambda-powertools/tracer";
import { LambdaInterface } from "@aws-lambda-powertools/commons";

const tracer = new Tracer();

export class Lambda implements LambdaInterface {
  @tracer.captureMethod()
  myMethod() {
    //other method is undefined as "this" is no longer the Lambda class
    this.otherMethod();
  }

  otherMethod() {
    console.log("other method");
  }

  @tracer.captureLambdaHandler()
  public async handler(_event: any, _context: any): Promise<void> {
    this.myMethod();
  }
}

export const handlerClass = new Lambda();
export const handler = handlerClass.handler;
```

Given that you have already opened a PR to fix this I'm gonna assign the issue to you.

**Comment by misterjoshua** [comment] 2022-08-12 16:32
@dreamorosi Hey. I tested `@tracer.captureMethod()` in the recently released v1.1.0. Although #1026 was included, I don't believe this issue was successfully fixed. Here is an example of code that does not work:

```ts
import { Tracer } from '@aws-lambda-powertools/tracer';

test('bug', async () => {
  const tracer = new Tracer();

  class BugClass {
    constructor(private readonly callback: () => string) {}

    @tracer.captureMethod()
    async getFoo(): Promise<string> {
      return this.callback();
    }
  }

  const myClass = new BugClass(() => 'somevalue');
  await expect(myClass.getFoo()).resolves.toEqual('somevalue');
});
```

Here is a screenshot demonstrating the unexpected error:

![image](https://user-images.githubusercontent.com/644092/184401992-94ef6e41-3457-4ee0-8104-aacfa913ec3a.png)

And here is a file from a repository that can reproduce the issue:
https://github.com/misterjoshua/lpt-tracer-bug/blob/main/test/bug.test.ts

You can test this for yourself by typing the following:

```shell
git clone https://github.com/misterjoshua/lpt-tracer-bug.git
cd lpt-tracer-bug
yarn install
yarn test
```

**Comment by dreamorosi** [comment] 2022-08-12 17:07
After looking into it a bit more it seems that the issue is not anymore related to how `this` is bound but instead to `readonly` attributes/methods of the decorated class.

For instance, the example below works as expected: 

```ts
import { Tracer } from "@aws-lambda-powertools/tracer";
import { LambdaInterface } from "@aws-lambda-powertools/commons";

const tracer = new Tracer({ serviceName: "serverlessAirline" });

class BugClass {
  constructor() {}

  private ok(): void {
    console.log("HELLO");
    return;
  }

  @tracer.captureMethod()
  async getFoo(): Promise<void> {
    return this.ok();
  }
}

class Lambda implements LambdaInterface {
  @tracer.captureMethod()
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  public async dummyMethod(): Promise<string> {
    return `otherMethod:${this.otherMethod()}`;
  }

  @tracer.captureLambdaHandler()
  public async handler(_event: any, _context: any): Promise<string> {
    const bugClass = new BugClass();
    await bugClass.getFoo();

    return await this.dummyMethod();
  }

  public otherMethod(): string {
    return "otherMethod";
  }
}

export const myFunction = new Lambda();
export const handler = myFunction.handler;
```

![Screenshot 2022-08-12 at 18 44 49](https://user-images.githubusercontent.com/7353869/184408679-50208b32-8503-45dd-a881-aba715c0c526.png)


To be honest I'm not sure if this is an expected behavior in TS decorators, I'd have to investigate more. But definitely I would consider this a separate issue from the first one that you reported - which was very valid and that was fixed.

**Comment by dreamorosi** [comment] 2022-08-13 20:12
Closing this in favor of #1056

**Closed by dreamorosi** 2022-08-13 20:12 UTC
Labels: tracer
