### ISSUE TITLE
Bug: missing AWS Lambda trace data for X-Ray

### ISSUE THREAD

**Issue by login21** [aws-powertools/powertools-lambda-typescript#1071] opened 2022-08-23 00:29 UTC
Hi ,

I need support to resolve this issue when I use powertool tracing with my serverless lambda function which has an Init() function.

```
2022-08-12T02:16:10.373Z	undefined	ERROR	Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.
    at Object.contextMissingLogError [as contextMissing] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:22:27)
    at Segment.resolveLambdaTraceData (/var/task/node_modules/aws-xray-sdk-core/dist/lib/env/aws_lambda.js:86:49)
    at Object.getSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:92:25)
    at Object.resolveSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:71:25)
    at captureOutgoingHTTPs (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:84:37)
    at Object.captureHTTPsRequest [as request] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:175:16)
    at RedirectableRequest._performRequest (/var/task/node_modules/follow-redirects/index.js:279:24)
    at new RedirectableRequest (/var/task/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/var/task/node_modules/follow-redirects/index.js:487:14)
    at dispatchHttpRequest (/var/task/node_modules/axios/lib/adapters/http.js:242:25)
	
2022-08-12T02:16:10.340Z	undefined	ERROR	Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.
    at Object.contextMissingLogError [as contextMissing] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:22:27)
    at Segment.resolveLambdaTraceData (/var/task/node_modules/aws-xray-sdk-core/dist/lib/env/aws_lambda.js:86:49)
    at Object.getSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:92:25)
    at Object.resolveSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:71:25)
    at captureOutgoingHTTPs (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:84:37)
    at TunnelingAgent.captureHTTPsRequest [as request] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:175:16)
    at TunnelingAgent.createSocket (/var/task/node_modules/tunnel/lib/tunnel.js:126:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/var/task/node_modules/tunnel/lib/tunnel.js:207:41)
    at TunnelingAgent.addRequest (/var/task/node_modules/tunnel/lib/tunnel.js:84:8)
    at new ClientRequest (_http_client.js:305:16)
	
2022-08-12T02:16:10.339Z	undefined	ERROR	Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.
    at Object.contextMissingLogError [as contextMissing] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:22:27)
    at Segment.resolveLambdaTraceData (/var/task/node_modules/aws-xray-sdk-core/dist/lib/env/aws_lambda.js:86:49)
    at Object.getSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:92:25)
    at Object.resolveSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:71:25)
    at captureOutgoingHTTPs (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:84:37)
    at Object.captureHTTPsRequest [as request] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:175:16)
    at RedirectableRequest._performRequest (/var/task/node_modules/follow-redirects/index.js:279:24)
    at new RedirectableRequest (/var/task/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/var/task/node_modules/follow-redirects/index.js:487:14)
    at dispatchHttpRequest (/var/task/node_modules/axios/lib/adapters/http.js:242:25)	
```
app.js file -

```
import express from 'express';
import * as OpenApiValidator from 'express-openapi-validator';
import multer from 'multer';
import ProxyAgent from 'proxy-agent';
import AWS from 'aws-sdk';
import { productsRouter } from './routes/products.js';
import config from './config/config.js';
import { providerRouter } from './routes/provider.js';
import { apisRouter } from './routes/apis.js';
import { errorHandler } from './middleware/errorHandler.js';
import { initExecutionContext, setExecutionContextLogAttributes } from './middleware/executionContext.js';
import { multipartOpenAPIValidatorAdaptor } from './middleware/multipartOpenAPIValidatorAdaptor.js';
import { multipartFileValidator } from './middleware/multipartFileValidator.js';
import {
  retrieveSsmParameters,
  initialiseTokenVerifier,
  fetchAndCacheJwks,
  fetchAndCacheCsgPublicKey
} from './authorization/authorizationConfig.js';
import { globalsSingleton } from './globals/globals.js';
import { logger } from './utils/logger.js';
import { getCorsOptions } from './utils/cors.js';
import cors from 'cors';
import { Request } from 'express';
import { tracer } from './utils/powertool.js';

const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

AWS.config.update({
  region: 'ap-southeast-2'
});
logger.info(`Instantiate Express Application`);
const app = express();

const networkProxy = config['NETWORK_PROXY'];
logger.info('networkProxy: ', { data: { networkProxy: networkProxy } });

const globals = globalsSingleton.getInstance();
let publicKey: any;
let idTokenVerifier: any;

const init = async () => {
  logger.info('Init function triggered.');
  await retrieveSsmParameters();
  if (networkProxy) {
    idTokenVerifier = await initialiseTokenVerifier(globals.getAuthorizationConfig()?.PORTAL_CLIENT_ID as string);
    await fetchAndCacheJwks(idTokenVerifier);
  } else {
    logger.error(`authorization configuration could not be setup as no network proxy configured.`);
    throw new Error(`authorization configuration could not be setup as no network proxy configured.`);
  }
  publicKey = await fetchAndCacheCsgPublicKey();
};

await init();
globals.setPublicKey(publicKey);
globals.setTokenVerifier(idTokenVerifier);
logger.info('Init function finished: ', {
  data: {
    publicKey: globals.getPublicKey(),
    idTokenVerifier: globals.getTokenVerifier()
  }
});

const corsOptions = function (req: Request, callback: (err: Error | null, options?: cors.CorsOptions) => void) {
  const requestOrigin = req.header('Origin') || req.header('origin');
  const opts = getCorsOptions(config.CORS_WHITELIST, requestOrigin as string) ; 

  logger.info('options =', opts);
  callback(null, opts);
};

app.use(cors(corsOptions));

app.use(express.urlencoded({ limit: '10mb', extended: true }));
app.use(express.json({ limit: '10mb' }));
app.use(upload.any());
app.use(initExecutionContext);
app.use(setExecutionContextLogAttributes);
app.use(multipartFileValidator);
app.use(multipartOpenAPIValidatorAdaptor);
app.use(
  OpenApiValidator.middleware({
    apiSpec: './api-spec/management-service-api-spec.yml',
    fileUploader: false
  })
);

app.use(`${config.BASE_PATH_V1}/providers`, providerRouter);
app.use(`${config.BASE_PATH_V1}/apis`, apisRouter);
app.use(`${config.BASE_PATH_V1}/products`, productsRouter);
app.use(errorHandler);

export { app };
```

My ssm call code looks like this -

```
export const getSsmParameters = async (keys: string[]) => {
  logger.debug('SSM client key: ', { data: { key: keys } });
  const params: GetParametersRequest = {
    Names: keys
  };
  try {
    const param = await ssm.getParameters(params).promise();
    return param.Parameters;
  } catch (err) {
    logger.error('SSM client failed retrieving parameters: ', { data: { error: err } });
    throw err;
  }
};
```
I am using captureAWSClient() function like this 

```
import AWS from 'aws-sdk';
const ssm = AWSXRay.captureAWSClient(new AWS.SSM());
```

Can anyone please help me fix this issue.

Few point about this issue -

- Active tracing in enabled in my lambda.
- Able to see the trace with other services like S3, Lambda, StepFunction etc.
- Have a init() function in my lambda code where I am calling the above ssm function to get values from parameter store.

**Comment by dreamorosi** [comment] 2022-08-23 07:37
Hi @login21, thank you for opening the issue and for using Powertools.

Before commenting on what could be the issue, I would like to understand your code better. 

If I understand correctly, you're setting up an Express app in the Lambda function. This app has a few routes (the ones towards the end of the code snippet) and has a function that you'd like to run the first time `app` is initialized, so that you can fetch some secrets. This initialization step is the `init` function you're mentioning.

Now, when a new request comes, two things can happen:
1. this is the first request** so the whole app is _created_, and the `init` function is run before then evaluating which router will be executed
2. this is a subsequent request** so Lambda reuses the `app` that was initialised earlier and skips directly to the router.

** Note: here when I say "first request" or "subsequent request" I'm really referring to the [Lambda execution environment and its lifecycle](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html). In reality you could have multiple execution environments running at the same time if there's enough request volume, since a function can handle only one request at the time.

With the above in mind, you're trying to trace a call to SSM that happens in the `init` function, and you're getting the errors you shared above.

Is my understanding somewhat correct? If not, could you please clarify any point I might have gotten wrong?

**Comment by dreamorosi** [comment] 2022-08-23 09:08
https://github.com/aws/aws-xray-sdk-node/issues/526

**Comment by login21** [comment] 2022-08-23 13:33
Hi @dreamorosi thank you so much for your response.

Yes your understanding is completely right. My init() function calls some other functions which then have call to aws ssm and also some third party apis.. I see the mentioned error in my Init() function.

**Comment by dreamorosi** [comment] 2022-08-23 14:10
Okay, understood, thanks for confirming.

If that's the case then the issue is somewhat expected. Let's take a look at what the error says:
> Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.

As the message suggests X-Ray is not able to determine where to append the tracing info. 

The error then provides two possible causes for this:
- `Ensure Active Tracing is enabled` - this is not your case since you're able to see other trace info + you confirmed it's enabled
- `Ensure [...] no subsegments are created outside the function handler.` - let's unpack this one

As we have established you are trying to trace some actions that are running in the `init` function and that are essentially executed **before** any of the requests are processed. The phase in which you're running these actions is called `Initialization` phase.

The `Initialization` subsegment represents the init phase of the Lambda execution environment lifecycle. During this phase, Lambda creates or unfreezes an execution environment with the resources you have configured, downloads the function code and all layers, initializes extensions, initializes the runtime, and runs the function's initialization code.

When a request reaches your router, or generally speaking, the Lambda function handler, a new phase begins and it's called `Invocation`.

The Invocation subsegment represents the invoke phase where Lambda invokes the function handler. This begins with runtime and extension registration and it ends when the runtime is ready to send the response.

>  **Note**
> In Lambda, **you can use the X-Ray SDK to extend the Invocation subsegment** with additional subsegments for downstream calls, annotations, and metadata. **You can't access the function segment directly or record work done outside of the handler invocation scope**.

So essentially, you're right in having these actions run outside of the handler, so that they can be reused across subsequent invocations. With that said however, the fact that you're getting the error is expected as X-Ray does not allow you to add trace data to the `Initialization` phase in which these actions live.

As an alternative, if you really would like to trace these actions, you could have a code that looks like this:
```ts

const init = () => {
  // ..init stuff

  globals.setPublicKey(publicKey);
  globals.setTokenVerifier(idTokenVerifier);
}

const router1 = () => {
  if (globals.hasPublicKey === false || globals.hasTokenVerifier === false) {
    await init()
  }

  // process the request
}

const router2 = () => {
  // TODO: Implement these two methods on `globals`
  if (globals.hasPublicKey() === false || globals.hasTokenVerifier() === false) {
    await init()
  }

  // process the request
}

app.use(`/route1`, router1);
app.use(`/route1`, router2);
```

In that way, the `init` function would still be run only once (the first request), but in this case since it's executed as part of the handler scope it should work.

**Note 1:** The code above might not be valid ExpressJS code, but it's just to give you an idea of how the implementation would look like. 
**Note 2:** The code above is provided only for informative purposes. You're solely responsible of implementing / reviewing it / and ultimately deciding to use it in your code. We won't offer any additional support on in.

You can read more about these phases and concepts [here](https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html). Also since this is not really an issue with Powertools but more of a limitation of the service, I'm going to be closing the issue.

**Closed by dreamorosi** 2022-08-23 14:10 UTC
Labels: tracer

**Comment by login21** [comment] 2022-08-24 00:17
Hi @dreamorosi I will try modifying my code as per your suggestion and see if that works for me.

I would also like to know if there is way I can stop seeing this error messages like I read on AWS Xray docs that setting "AWS_XRAY_CONTEXT_MISSING" environment variable can be useful to avoid throwing exceptions. I tried this one but it didn't work for me. I am okay to not trace my init() function and trace other things.

**Comment by dreamorosi** [comment] 2022-08-24 10:10
Hey @login21, yes.

You could suppress the errors using the `setContextMissingStrategy` method on `Tracer.provider` that is [documented here](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/api/interfaces/_aws_lambda_powertools_tracer._internal_.ProviderServiceInterface.html#setContextMissingStrategy):
```ts
import { Tracer } from "@aws-lambda-powertools/tracer";

const tracer = new Tracer();
// This line below disables all errors completely
tracer.provider.setContextMissingStrategy(() => ({}));
```

Alternatively, you could instruct the X-Ray SDK to emit an error log instead of throwing one by using
```ts
tracer.provider.setContextMissingStrategy("LOG_ERROR");
```

I would however advise against using either of these in a production environment as you'd be essentially suppressing all errors related to the context, not just the ones related to the `init` function.

If you are not interested in tracing the `init` function, simply don't capture the SSM client or create a new one specifically for that function, so that tracing is not applied to that call.

**Comment by login21** [comment] 2022-08-25 00:35
Hi @dreamorosi Thanks again for your quick response. 

Well that's what I was doing at the very beginning when I got those error. I tried removing tracing from all the places which were getting invoked in my init() function and still I was seeing these errors. There are some http calls in my functions and those functions are getting invoked in init but there is no tracing in those functions/files so I wonder why these errors.

`
2022-08-25T00:24:47.187Z	undefined	ERROR	Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.    at Object.contextMissingLogError [as contextMissing] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:22:27)    at Segment.resolveLambdaTraceData (/var/task/node_modules/aws-xray-sdk-core/dist/lib/env/aws_lambda.js:86:49)    at Object.getSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:92:25)    at Object.resolveSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:71:25)    at captureOutgoingHTTPs (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:84:37)    at Object.captureHTTPsRequest [as request] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:175:16)    at features.constructor.handleRequest (/var/task/node_modules/aws-sdk/lib/http/node.js:45:23)    at executeSend (/var/task/node_modules/aws-sdk/lib/event_listeners.js:370:29)    at Request.SEND (/var/task/node_modules/aws-sdk/lib/event_listeners.js:384:9)    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:102:18)

2022-08-25T00:24:47.327Z	undefined	ERROR	Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.    at Object.contextMissingLogError [as contextMissing] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:22:27)    at Segment.resolveLambdaTraceData (/var/task/node_modules/aws-xray-sdk-core/dist/lib/env/aws_lambda.js:86:49)    at Object.getSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:92:25)    at Object.resolveSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:71:25)    at captureOutgoingHTTPs (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:84:37)    at Object.captureHTTPsRequest [as request] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:175:16)    at RedirectableRequest._performRequest (/var/task/node_modules/follow-redirects/index.js:279:24)    at new RedirectableRequest (/var/task/node_modules/follow-redirects/index.js:61:8)    at Object.request (/var/task/node_modules/follow-redirects/index.js:487:14)    at dispatchHttpRequest (/var/task/node_modules/axios/lib/adapters/http.js:242:25)

2022-08-25T00:24:47.328Z	undefined	ERROR	Error: Missing AWS Lambda trace data for X-Ray. Ensure Active Tracing is enabled and no subsegments are created outside the function handler.    at Object.contextMissingLogError [as contextMissing] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:22:27)    at Segment.resolveLambdaTraceData (/var/task/node_modules/aws-xray-sdk-core/dist/lib/env/aws_lambda.js:86:49)    at Object.getSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:92:25)    at Object.resolveSegment (/var/task/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:71:25)    at captureOutgoingHTTPs (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:84:37)    at TunnelingAgent.captureHTTPsRequest [as request] (/var/task/node_modules/aws-xray-sdk-core/dist/lib/patchers/http_p.js:175:16)    at TunnelingAgent.createSocket (/var/task/node_modules/tunnel/lib/tunnel.js:126:25)    at TunnelingAgent.createSecureSocket [as createSocket] (/var/task/node_modules/tunnel/lib/tunnel.js:207:41)    at TunnelingAgent.addRequest (/var/task/node_modules/tunnel/lib/tunnel.js:84:8)    at new ClientRequest (_http_client.js:305:16)

`
