### ISSUE TITLE
Maintenance: remove a dependency to deprecated library `@aws-sdk/util-base64-node`

### ISSUE THREAD

**Issue by yamatatsu** [aws-powertools/powertools-lambda-typescript#2246] opened 2024-03-18 13:27 UTC
### Summary

Let's remove a deprecated dependency. See, https://www.npmjs.com/package/@aws-sdk/util-base64-node.

### Why is this needed?

Following warning is shown on installing `@aws-lambda-powertools/parameters`;
<img width="628" alt="image" src="https://github.com/aws-powertools/powertools-lambda-typescript/assets/11013683/a1ed6cfb-8372-4d65-bbd9-fc5ecad0ede6">

### Which area does this relate to?

Parameters, Idempotency

### Solution

About idempotency, remove the dependency because it is not used.
About parameters, replace it to `@smithy/util-base64`.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment] 2024-03-18 15:39
Thank you for taking the time to open the issue.

This is a duplicate of #1915, which has a long form explanation of why we kept the dependency around rather than upgrading to the newer one.

Since then, we have invested time in writing our own little utility to convert from base 64 encoded data (#2188), so we should move the Parameters utility to use that instead.

I'm more than happy to review and merge a PR that does that as well as removing the dependency from the Idempotency utility, but I'd be inclined to block the current PR that instead upgrades to the `@smithy` dependency.

Let me know if that works for you or you have any questions.

**Closed** 2024-03-26 10:33 UTC
Labels: parameters
