### ISSUE TITLE
Bug: Unable to use ESM bundling in AWS Lambda / Nodejs 14.x

### ISSUE THREAD

**Issue by revmischa** [aws-powertools/powertools-lambda-typescript#490] opened 2022-01-19 14:54 UTC
## Bug description

If you enable ["ESM" bundling with NodejsFunction](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.OutputFormat.html) you get this error:

```
	{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"util\" is not supported",
    "stack": [
        "Error: Dynamic require of \"util\" is not supported",
        "    at file:///var/task/index.mjs:1:820",
        "    at null.<anonymous> (/node_modules/cls-hooked/context.js:4:14)",
        "    at file:///var/task/index.mjs:1:1067",
        "    at null.<anonymous> (/node_modules/aws-xray-sdk-core/dist/lib/context_utils.js:5:11)",
        "    at file:///var/task/index.mjs:1:1067",
        "    at null.<anonymous> (/node_modules/aws-xray-sdk-core/dist/lib/aws-xray.js:2:20)",
        "    at file:///var/task/index.mjs:1:1067",
        "    at null.<anonymous> (/node_modules/aws-xray-sdk-core/dist/lib/index.js:3:18)",
        "    at file:///var/task/index.mjs:1:1067",
        "    at null.<anonymous> (/node_modules/@aws-lambda-powertools/tracer/src/provider/ProviderService.ts:4:1)"
    ]
}
```

### Expected Behavior

Would like to use xray with ESM.

### Steps to Reproduce

I'm using middy with the tracer middleware. I get the above error when I set
`format: OutputFormat.ESM`

### Environment

* **Powertools version used**: 0.3.3
* **Packaging format (Layers, npm)**: nodejsfunction
* **AWS Lambda function runtime:** node 14
* **Debugging logs:**

**Comment by flochaz** [comment] 2022-01-19 15:03
Thank you for reporting it. We will have a look asap.

**Comment by flochaz** [comment] 2022-01-21 09:18
As reported by @dreamorosi, the issue is on xray-sdk side. We will follow https://github.com/aws/aws-xray-sdk-node/issues/482 resolution carefully.

**Comment by dreamorosi** [comment] 2022-05-12 08:11
I'm going to close this issue in favor of #521 where we will be tracking efforts to support ESM bundling in Powertools.

**Closed by dreamorosi** 2022-05-12 08:11 UTC
Labels: tracer, blocked, bug-upstream
