### ISSUE TITLE
Maintenance(layer): add canary tests to layer deployment steps

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1571] opened 2023-07-03 14:10 UTC
### Summary

Similar to the python deployment pipeline we need a canary deployment for layers in beta and prod env, so we can make sure that the layer we release can be imported attached to a function. This is not an e2e test for the layer, but for the release process, because we might get the configuration wrong by passing invalid version to the workflow step. See #1569. 

### Why is this needed?

To prevent misconfiguration of the layer packaging during release.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment] 2023-07-03 15:18
Possibly a duplicate of #1355

**Comment by am29d** [comment] 2023-07-03 16:12
Yep, I filtered by `area/layer` and did not find any thing. Thanks.

**Closed** 2023-07-03 16:11 UTC
Labels: automation, layers
