### ISSUE TITLE
Bug: log sampling is not working in v2

### ISSUE THREAD

**Issue by theburningmonk** [aws-powertools/powertools-lambda-typescript#2668] opened 2024-06-18 12:30 UTC
### Expected Behavior

When `POWERTOOLS_LOG_SAMPLE_RATE` is set to `0.1` and every invocation includes a call to `logger.refreshSampleRateCalculation()` to recalculate the sampling rate, the debug logs should be recorded for only 10% of invocations.

### Current Behavior

The sampling decision is made at cold start, and then all invocations afterwards will either log all debug logs or none at all. The refreshSampleRateCalculation() method is not giving the correct behaviour.

### Code snippet

This line is included at the start of a handler function: 

```
logger.refreshSampleRateCalculation()
```

The `POWERTOOLS_LOG_LEVEL` env var is set to `ERROR`. 
The `POWERTOOLS_LOGGER_SAMPLE_RATE` env var is set to `0.1`

### Steps to Reproduce

Create a function with:
* `POWERTOOLS_LOGGER_SAMPLE_RATE` env var set to `0.1`
* `POWERTOOLS_LOG_LEVEL` env var set to `ERROR`
* include a call to logger.refreshSampleRateCalculation() at the start of the handler
* include a few debug logs
Invoke the function multiple times to see sampling decision is taken once, at cold start, but then never changed on subsequent invocations on the same worker

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment] 2024-06-18 12:43
Hi @theburningmonk, thank you for opening the issue.

As I mentioned in [the thread](https://x.com/theburningmonk/status/1803008698618380357) we exchanged I think the report is valid and we have a bug.

I am currently investigating and I will share more info once I have a definitive answer.

**Comment by dreamorosi** [comment] 2024-06-19 09:56
Hi Yan, just wanted to let you know that I identified the bug and that I have already opened a PR with a proposed fix.

The root cause of the bug was the one that I hinted at yesterday during our exchange on Twitter. Basically we were not restoring the log level to the original one after having sampled a specific invocation.

Once the PR is merged it will be included in the next release.

In the meanwhile, if you want to continue upgrading before the release, a workaround like this would work:

```diff
import { Logger } from '@aws-lambda-powertools/logger';

const logger = new Logger({ sampleRateValue: 0.1, logLevel: 'ERROR' });

export const handler = async () => {
+ logger.setLogLevel('ERROR'); // TODO: remove after next release
  logger.refreshSampleRateCalculation();
  
  logger.debug('This is a debug message - should not appear every time');

  return {
    statusCode: 200,
    body: JSON.stringify("Hello, World!"),
  };
};
```

**Closed** 2024-06-19 10:01 UTC
Labels: logger
