### ISSUE TITLE
Bug: Middy requires special flag in `tsconfig.json` to be imported as esm

### ISSUE THREAD

**Issue by asenousy** [aws-powertools/powertools-lambda-typescript#465] opened 2022-01-14 10:26 UTC
## Bug description

when using middy i get the following error `TypeError: core_1.default is not a function`

### Possible Solution

updating the tsconfig.json with `"esModuleInterop": true` solved the problem as suggested in middy's github Issue https://github.com/middyjs/middy/issues/203

### Environment

* **Powertools version used**: 0.2.0
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** node v14

**Comment by dreamorosi** [comment] 2022-01-14 16:34
Hello @asenousy, thanks for opening this issue. Just for context we are using that same config in the `tsconfig.json` files of our packages (i.e. [here](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/tsconfig.json#L16)). We'll be looking at this and get back to you.

**Comment by willfarrell** [comment] 2022-01-26 15:58
In middy v3 (alpha already released) we plan to make esm the default, possibly making this a non-issue.

**Comment by peledni** [comment] 2022-01-30 22:25
A workaround for those of us who can't use "esModuleInterop" : true in tsconfig:
```typescript
import * as MiddyTypes from '@middy/core';
const middy = require('@middy/core') as typeof MiddyTypes.default;
```

**Comment by ijemmy** [comment] 2022-02-15 10:04
Put this `on-hold` as this will be solved when we upgrade to middy v3.

@saragerion  I wonder if we should make this note in our doc? (for all utils, in middy tab). On the other hand, this is middy specific and [middy v3](https://github.com/middyjs/middy/issues/626) will be released when NodeJS16 is supported in Lambda. We can wait to just upgrade once.  

I'm inclined to wait and upgrade as we aren't out of beta yet. What's your thought?

**Comment by willfarrell** [comment] 2022-02-15 17:56
Using ESM by default in Middy *was* the plan. However ...

(a) Recent discoveries that Lambda with ESM cannot access node_modules pre-bundled in the runtime or shared in a lambda layer has made us stop and rethink. This isn't documented anywhere that I know of :(. I've reported this regression to AWS Support and was told to use v3 of the SDK instead.

(b) We would consider migrating to using v3 of the SDK (I even tried a year ago), however, RDS.Signer is not implemented yet (https://github.com/aws/aws-sdk-js-v3/issues/1823 @AllanZhengYP). Using v3 of the SDK would increase lambda bundle size compared to v2 of the SDK. I would suggest AWS pre-bundle all v3 packages in the runtime (https://github.com/aws/aws-sdk-js-v3/issues/2149), but this wouldn't help with ESM support because lambda handlers wouldn't be able to access them anyways (a) :shrug:

(c) Even if (a), or (b*2) are resolved, the X-Ray SDK using dynamic require breaks when using ESM (https://github.com/aws/aws-xray-sdk-node/issues/482 @NathanielRN).

Based on the current state of ESM support from AWS outlined above, the new plan for middy@3 will be to continue providing CommonJS for another year sadly. We're going to wait (2-3 week) and see if ((a OR b*2) AND c) are resolved before making a final decision and mint a beta release.

Cross posted from: https://github.com/middyjs/middy/issues/584

cc @lmammino

**Comment by dreamorosi** [comment] 2022-02-28 14:38
At the moment this project does not guarantee support for ESM builds, we have a dedicate issue to track this topic which you can subscribe to get updates: #521

Closing this issue.

**Closed by dreamorosi** 2022-02-28 14:38 UTC
Labels: bug-upstream
