### ISSUE TITLE
Bug: Subsegment too large to send

### ISSUE THREAD

**Issue by nathanagez** [aws-powertools/powertools-lambda-typescript#1310] opened 2023-02-18 00:02 UTC
### Expected Behaviour

When using `captureAWSv3Client` method we expect the trace to contain all segments (even with a huge amount on API calls to DynamoDB via the SDK).
The screenshot below shows the behavior when we use `captureAWSv3Client` from the `aws-xray-sdk` directly.

![expected-behavior](https://user-images.githubusercontent.com/7148684/219818314-82fe8325-67f7-4879-a271-1b1413923712.png)

### Current Behaviour

We noticed when using the Tracer from `aws-lambda-powertools`, that a large amount of requests (in our case DynamoDB), the `Subsegment too large to send` error occurs.

![Screenshot 2023-02-18 at 00 16 25](https://user-images.githubusercontent.com/7148684/219818385-76e64b0f-4788-4b31-9710-ddcabeb214a8.png)

We can see in the screenshot below that we are missing the DynamoDB segments
![missing-dynamodb-segments](https://user-images.githubusercontent.com/7148684/219818427-d0504067-b085-459c-a13d-61e96af13dd2.png)

### Code snippet

use of `aws-lambda-powertool` snippet
```ts
import { Tracer, captureLambdaHandler } from '@aws-lambda-powertools/tracer';
import middy from '@middy/core';

const tracer = new Tracer({ serviceName: SERVICE_NAME });
const ddbClient = captureAWSv3Client(new DynamoDBClient({}));

// getChannelHandler contains a repository where we make all the DDB requests

export default middy<GetChannelsEvent>()
  .use(captureLambdaHandler(tracer))
  .handler(getChannelHandler);
```

use of `aws-xray-sdk` snippet
```ts
import { captureAWSv3Client } from 'aws-xray-sdk';
const ddbClient = captureAWSv3Client(new DynamoDBClient({}));

// getChannelHandler contains a repository where we make all the DDB requests

export default middy<GetChannelsEvent>()
  .handler(getChannelHandler);
```

### Steps to Reproduce

When we have a normal amount of requests (especially to DDB), we noticed the issue doesn't occur. However, to reproduce the issue I suppose that you need to do a lot of requests to DynamoDB at once (as you can see in the first screenshot). 
We are using a single table with DynamoDB and multiple repositories in order to rebuild the relationships between our different entities (that is why we have that amount of requests, especially for a GET all entity API route). 

### AWS Lambda Powertools for TypeScript version

latest

### AWS Lambda function runtime

14.x

### Packaging format used

Npm

**Comment by dreamorosi** [comment] 2023-02-18 00:11
Hi, thanks for opening the issue.

Could you also please share a code snippet of the working code that uses only the SDK, and sends all the segments correctly?

**Comment by dreamorosi** [comment] 2023-02-18 00:15
Hi, thank you for opening the issue.

We'll take a look at this next week and get back to you.

**Comment by nathanagez** [comment] 2023-02-18 00:20
Hi @dreamorosi, since the architecture of the project contains a lot of abstraction (DDD + Hexgonal architecture), the best I can provide is something like this:


```ts
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocument, GetCommand } from '@aws-sdk/lib-dynamodb';
import { captureAWSv3Client } from 'aws-xray-sdk';

import middy from '@middy/core';

const ddbClient = captureAWSv3Client(new DynamoDBClient({}));

const getChannelHandler = middy<any>()
  .handler(async (
    _event,
    _context,
  ) => {
    const documentClient = DynamoDBDocument.from(ddbClient, {
      marshallOptions: {
        convertEmptyValues: true,
        removeUndefinedValues: true,
      },
    });

    // But we have more than just a single DDB API call
    const command = new GetCommand({
      TableName: 'table-name',
      Key: {
        PK: 'uid',
        SK: 'somethingelse',
      },
    });
    return documentClient.send(command);
  });

export default middy<any>()
  .handler(getChannelHandler);

```

As you can see, the only differences are those lines 
- `import { captureAWSv3Client } from 'aws-xray-sdk';` 
- `const ddbClient = captureAWSv3Client(new DynamoDBClient({}));` 

As said, to reproduce it, you will probably need to have a lot more requests.

**Comment by dreamorosi** [comment] 2023-02-19 18:00
Hi Nathan, thank you for your patience.

I have been trying to reproduce the issue but I was not able to.

To help with troubleshooting I have created a sample app with the following resources:
- One DynamoDB Table
- Two Lambda functions, one that uses Powertools and at the other that uses only the X-Ray sdk for node

You can [find the sample application here](https://github.com/dreamorosi/test-1310) and you can optionally decide to deploy it in your account, if you'd like to verify the below.

Both functions are extremely trivial, but I believe should be enough to reproduce an issue related to capturing queries to DynamoDB using the AWS SDK.

The function that uses Powertools is as follows:
```ts
import { Tracer, captureLambdaHandler } from '@aws-lambda-powertools/tracer';
import middy from '@middy/core';
import { DynamoDBClient, GetItemCommand } from '@aws-sdk/client-dynamodb';

const tracer = new Tracer();
const ddbClient = tracer.captureAWSv3Client(new DynamoDBClient({}));

const myHandler = async (event: unknown): Promise<unknown> => {
  const params = {
    TableName: process.env.TABLE_NAME,
    Key: {
      id: { S: '123' },
    },
  };

  const items = [];
  // Request same item 1000 times
  for (let i = 0; i < 1000; i++) {
    const res = await ddbClient.send(new GetItemCommand(params));
    items.push(res.Item);
  }

  return items;
};

export const handler = middy(myHandler)
  .use(captureLambdaHandler(tracer))
```

The one that uses the SDK only instead is as follows:
```ts
import { captureAWSv3Client } from 'aws-xray-sdk-core';
import middy from '@middy/core';
import { DynamoDBClient, GetItemCommand } from '@aws-sdk/client-dynamodb';

const ddbClient = captureAWSv3Client(new DynamoDBClient({}));

const myHandler = async (event: unknown): Promise<unknown> => {
  const params = {
    TableName: process.env.TABLE_NAME,
    Key: {
      id: { S: '123' },
    },
  };

  const items = [];
  // Request same item 1000 times
  for (let i = 0; i < 1000; i++) {
    const res = await ddbClient.send(new GetItemCommand(params));
    items.push(res.Item);
  }

  return items;
};

export const handler = middy()
  .handler(myHandler);
```

Both functions follow a very similar structure in that they both initialize a DynamoDB client outside of the handler, capture it, and then within the main handler make 1000 API calls to the table to read an item. Finally, they both return the item.

In my test both the Powertools function and the SDK one are traced correctly and the full traces show in the CloudWatch console. Below you can find a video where I show the code, invoke the function, and then show you the traces (if you want to skip the code part, go to minute 1):

https://user-images.githubusercontent.com/7353869/219962546-61a2ffc2-b499-4b52-9490-ea4ad7ef4770.mp4

For full disclaimer, the two examples are not 100% equivalent. When using the `captureLambdaHandler` middleware, Powertools automatically creates an additional segment that is not present in the pure SDK one. So functions traced with Powertools will always have traces with a similar structure:
```
Invocation
  ### index.handler
    DynamoDB
    DynamoDB
    ...
    DynamoDB
```

While ones traced with the SDK, unless manually instrumented to do so, will show traces like so:
```
Invocation
  DynamoDB
  DynamoDB
  ...
  DynamoDB
```

So, obviously your function's logic is likely more complex and also the items being read from DynamoDB might be both more in quantity and bigger in size. With that said however, and considering what discussed in the PR about streaming threshold being 0 in Lambda, I'm not 100% certain as to why the issue is happening in your environment.

One thing that comes to mind however, is that the `captureLambdaHandler` middleware automatically captures the response returned by the handler and adds it as metadata to the main segment (`### index.handler`). If the response being returned is too big, once attached to the main segment, it could cause the segment to become too big to be streamed and thus be rejected and never reach the X-Ray daemon. In this case, since all the DynamoDB segments are children of this segment, the X-Ray service won't be able to correlate them and so you'll have missing data in the console.

Assuming that the DynamoDB segments are all within the allowed size (they show in the SDK-only example after all), and that each one of them is streamed immediately as soon as it's closed, the _culprit_ could be the feature I've just described.

To test this, could you please try to [disable it](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/tracer/#disabling-response-auto-capture) and run the function again? You can disable it by either passing an argument to the middleware, like this:
```ts
export const handler = middy(myHandler)
  .use(captureLambdaHandler(tracer, { captureResponse: false }))
```
or via environment variable `POWERTOOLS_TRACER_CAPTURE_RESPONSE=false`.

**Comment by nathanagez** [comment] 2023-02-20 11:25
Hi @dreamorosi, thanks a lot for taking time debugging the issue. After testing to disable the response capture, i.e.: 

```ts
export const handler = middy(myHandler)
  .use(captureLambdaHandler(tracer, { captureResponse: false }))
```

it looks like we now receive all the data within the AWS Console. Based on your pretty clear explanation I now better understand what was causing the issue.

**Comment by dreamorosi** [comment] 2023-02-20 11:36
That's great to hear! 

One thing I forgot to mention in my previous message is that if you still require/would like to capture some of the response of your handler, you can still do so by manually calling `tracer.addResponseAsMetadata(data)`. This will automatically add the `data` as metadata to the current active segment with key `response ${name of the segment}`.  In your case, you might want to put it right before returning.

I'm going to close the issue but leave the title as it is, so that it may help others searching for a similar keyword.

**Closed by dreamorosi** 2023-02-20 11:36 UTC
Labels: tracer
