### ISSUE TITLE
Feature request: Support Middy 5.x

### ISSUE THREAD

**Issue by saragerion** [aws-powertools/powertools-lambda-typescript#2049] opened 2024-02-11 22:47 UTC
### Use case

This feature request is about an upcoming official support of [Middy](https://github.com/middyjs/middy) 5.x. 

The current Powertools version 1.18.0 officially supports Middy up until version 3, as described in the [documentation](https://docs.powertools.aws.dev/lambda/typescript/1.18.0/core/logger/#capturing-lambda-context-info).

Support for Middy v4 is expected to be launched soon as part of [the upcoming major release 2.x](https://github.com/aws-powertools/powertools-lambda-typescript/issues/1694#issuecomment-1790427042).

If and when Middy v5 will be officially supported, it would be good to guide developers on what changes they need to implement in their codebase to successfully leverage the Logger utility together with Middy v5.

### Solution/User Experience

Upgrading to Middy v5 may have a significant impact on the codebase and developer experience.
See Middy's [documentation](https://middy.js.org/docs/upgrade/4-5/) for more info.

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment] 2024-02-12 07:16
Hi @saragerion thank you for opening this issue.

At the moment we don't have concrete plans for officially supporting Middy.js v5, however when the time comes I expect there will be challenges due to Powertools supporting both CJS and ESM and Middy.js having dropped support for the former in their v5 major version.

According to [our versioning policy](https://docs.powertools.aws.dev/lambda/typescript/latest/versioning/#dependency-lifecycle) we are committed to supporting all current AWS Lambda managed runtimes, which at the time of writing are the ones corresponding to Node.js 16 through Node.js 20.

On Middy.js side, [their release cadence](https://middy.js.org/docs/intro/release-cycle) aligns more closely with the Node.js LTS policy. This means that v5 dropped support for Node.js 16.

For the time being, I'd suggest customers to stick with v4 if they're using mainly the `@middy/core` module (the only one required by Powertools' middlewares), [as suggested](https://github.com/middyjs/middy/issues/1148#issuecomment-1849043767) by Middy.js own maintainer.

With this in mind, and according to the latest info publicly available on the [AWS Lambda Runtime versioning policy](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), the earliest we can consider support for Middy.js 5x is going to be late Q2/early Q3, which is when we're expected to also drop support for Node.js 16.

I'm going to mark this as an item to revisit in the next quarter, but it would be useful for us to have customers interested in the feature react with a 👍 to this issue as this will help us understand demand.

**Comment by dreamorosi** [comment] 2024-07-09 10:48
In the next release we are going to drop support for Node.js 16, which means we can now look into extending support to Middy.js v5.x.

Based on the reactions to my last message above, there seems to be significant interest in us adding support to Middy.js 5.x despite it dropping support for CJS.

I have already started testing some of our utilities with the newer version in some samples & demos, but before officially adding support we'll need to look into adding the version to our test matrix.

**Closed** 2024-07-10 09:11 UTC

**Comment by dreamorosi** [comment] 2024-08-13 18:05
As mentioned in the issue you've opened on middyjs/middy/#1208, this is most likely happening because you're transpiling your TypeScript code to CommonJS while Middy.js 5.x only supports ESM.

As the stack trace suggests, the root cause of the issue is Middy.js and not Powertools for AWS, nor AWS Lambda itself.

Without knowing how you are transpiling or bundling your code, I can't make any specific suggestions, but if you are using CDK like shared in the other issue, then you need to instruct `esbuild` to actually output ESM - we have an example of this [in the repo](https://github.com/aws-powertools/powertools-lambda-typescript/blob/f85cdd168f20c2fcb4f7e5bc3cca45ea4c6afeeb/examples/app/cdk/example-stack.ts#L89).

If this is still an issue and either **1/** you are sure that are using ESM but it still doesn't work, or [2/](https://github.com/aws-powertools/powertools-lambda-typescript/blob/f85cdd168f20c2fcb4f7e5bc3cca45ea4c6afeeb/examples/app/cdk/example-stack.ts#L89) would like Middy.js to support CJS, I would suggest to follow up with them on their repo.
